[package]
name = "language-tags"
version = "0.1.0"
authors = ["Pyfisch <pyfisch@gmail.com>"]
exclude = ["README.md", ".travis.yml", ".gitignore"]

description = "Language tags for Rust"
license = "MIT"
repository = "https://github.com/pyfisch/rust-language-tags"
documentation = "http://pyfisch.github.io/rust-language-tags/language_tags/"
keywords = ["language", "internationalization", "translation", "http", "html"]
