[package]
name = "language-tags"
version = "0.3.0"
authors = ["Pyfisch <pyfisch@gmail.com>"]

description = "Language tags for Rust"
license = "MIT"
repository = "https://github.com/pyfisch/rust-language-tags"
keywords = ["language", "internationalization", "translation", "http", "html"]

[badges]
travis-ci = { repository = "pyfisch/rust-language-tags" }

