[package]
name = "language-tags"
version = "0.0.4"
authors = ["Pyfisch <pyfisch@gmail.com>"]

description = "Language tags for Rust"
license = "MIT"
repository = "https://github.com/pyfisch/rust-language-tags"
